# Generated by Django 6.0.5 on 2026-08-19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icao_code", models.CharField(max_length=4, unique=True)),
                ("iata_code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=80)),
                ("department", models.CharField(max_length=80)),
                ("elevation_ft", models.PositiveIntegerField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("icao_code",)},
        )
    ]
